// Copyright 2014 Denis Bernard. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package util provides various utility functions for the Rand package
package util

import "github.com/db47h/rand64/splitmix64"

// SeedSlice is a helper function to seed a state array from a single uint64
// using the internal splitmix64 PRNG.
func SeedSlice(dst []uint64, seed uint64) {
	rng := splitmix64.New(seed)
	for i := range dst {
		dst[i] = rng.Uint64()
	}
}

// SeedFromSlice is a helper function to seed a state array dst given a slice
// of src uint64. If the source slice is too short, we complete with values
// generated by a splitmix64 PRNG
func SeedFromSlice(dst, src []uint64) {
	i := copy(dst, src)
	// fill in the missing bits
	if i < len(dst) {
		SeedSlice(dst[i:], dst[i-1])
	}
}
